# H5 file structure
gt_name: "label"
seg_name: "segmentation"

# Files location GT files and Segmentation files have to share a single ID number in order to be matched
gt_dir: TO BE FILL # Path to ground truth  directory files at full resolution or dictionary with tuple of ground truth and segmentation. Files must be h5
seg_dir: TO BE FILL # (Optional) Path to predicted segmentation files at any resolution. Files must be h5 or tiff

# train_config_file: # (Optional) Path to config file used for experiments
# (Optional) Segmentation Algorithm config file. Empty if it does not exists

seg_background_zero: True # If true the background (default label 0) is not modified in the evaluation script. If False, the larger object in the segmentation gets the label 0 and the pixels belonging to the ground truth gets masked out.

# Output
output_csv: "./test_config" # Path to output CSV file

# Custom notes, for comments not in the training configuration file
metadata: # (Optional)
  segmentation_algorithm: "MultiCut" # Segmentation algorithm
  down_sampling: [1, 2, 2] # For example if there is any down sampling
