
# model configuration
model:
  # model class
  name:
  # number of input channels to the model
  in_channels:
  # number of output channels
  out_channels:
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order:
  # feature maps scale factor
  f_maps:
  # basic module
  basic_module:
  # number of groups in the groupnorm
  num_groups:
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid:

# predictor configuration
predictor:
  # standard in memory predictor
  name: 'StandardPredictor'

# specify the test datasets
datasets:
  # patch size given to the network (adapt to fit in your GPU mem)
  patch: [100, 224, 224]
  # stride between patches (make sure the the patches overlap in order to get smoother prediction maps)
  stride: [40, 100, 100]
  # Define padding mode (Best to keep it True)
  mirror_padding: true
  # path to the raw data within the H5
  raw_internal_path: raw
  # how many subprocesses to use for data loading
  num_workers: 8

  transformer:
    test:
      raw:
        - name: Normalize
        - name: ToTensor
          expand_dims: true
