package:
  name: plantseg
  version: 1.0.0

source:
  git_rev: v1.0.0
  git_url: https://github.com/hci-unihd/plant-seg.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python 3.7
    - h5py
    - pywget
    - pyyaml
    - scipy =1.2
    - scikit-image
    - scikit-learn
    - tifffile
    - vigra
    - torchvision
    - pytorch
    - elf
    - gasp
    - pytorch-3dunet

test:
  requires:
    - pytest
  run:
    - pytest tests/
about:
  home: https://github.com/hci-unihd/plant-seg