package:
  name: plantseg
  version: 1.0.0

source:
  # git_rev: v1.0.0
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantseg = plantseg.main.plantseg:main

requirements:
  build:
    - python
    - pip

  run:
    - python 3.7
    - pillow<7
    - h5py
    - pywget
    - pyyaml
    - scipy =1.2
    - scikit-image
    - scikit-learn
    - tifffile
    - vigra
    - torchvision
    - pytorch
    - elf
    - gasp
    - pytorch-3dunet

test:
  requires:
    - pytest
  run:
    - pytest tests/
about:
  home: https://github.com/hci-unihd/plant-seg