package:
  name: plantseg
  version: environ.get('GIT_DESCRIBE_TAG', 'default')

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv;
  {{ PYTHON }} -m pip install https://github.com/abailoni/GASP/archive/refs/tags/v1.0.4.tar.gz#egg=gasp"
  number: 1

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pillow
    - h5py
    - pywget
    - pyyaml
    - scipy
    - scikit-image
    - scikit-learn
    - tifffile
    - vigra
    - torchvision
    - pytorch
    - elf
    - pytorch-3dunet

test:
  imports:
    - plantseg
    - plantseg.gui
    - plantseg.segmentation
  requires:
    - pytest
  run:
    - pytest
about:
  home: https://github.com/hci-unihd/plant-seg
  license: MIT
