model_path: '/g/kreshuk/wolny/workspace/for-pytorch-3dunet/FOR_paper_ovules/final/unet2d/bce_dice/ds3x/best_checkpoint.pytorch'
model:
  name: UNet2D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: 64
  num_groups: 8
  final_sigmoid: true
  is_segmentation: true
predictor:
  name: 'StandardPredictor'
  # padding to be removed from each axis in order to avoid block artifacts
  patch_halo: [0, 16, 16]
loaders:
  dataset: StandardHDF5Dataset
  batch_size: 32
  num_workers: 8
  mirror_padding: [0, 32, 32]
  raw_internal_path: raw
  label_internal_path: label
  test:
    file_paths:
      - '/g/kreshuk/wolny/Datasets/FlyWing/GT'

    slice_builder:
      name: SliceBuilder
      patch_shape: [1, 256, 256]
      stride_shape: [1, 128, 128]
      skip_shape_check: true

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true