cnn_postprocessing:
  factor: &id001
  - 1.0
  - 1.0
  - 1.0
  order: 2
  output_type: data_uint8
  state: false
  tiff: false
cnn_prediction:
  device: cuda
  mirror_padding: [16, 32, 32]
  model_name: confocal_unet_bce_dice_ds3x
  model_update: false
  patch:
  - 80
  - 170
  - 170
  state: true
  stride: Accurate (slowest)
  version: best
path: /g/kreshuk/wolny/Datasets/FlyWing/GT
preprocessing:
  factor:
  - 1.0
  - 1.0
  - 1.0
  filter:
    filter_param: 1.0
    state: false
    type: gaussian
  order: '2'
  save_directory: PreProcessing
  state: false
segmentation:
  beta: 0.9
  name: MultiCut
  post_minsize: 50
  run_ws: true
  save_directory: MultiCut1
  state: true
  ws_2D: true
  ws_minsize: 3
  ws_sigma: 2.0
  ws_threshold: 0.4
  ws_w_sigma: 0.0
segmentation_postprocessing:
  factor: *id001
  order: 0
  state: false
  tiff: false
