name: Deploy Python Package using Conda

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
    - name: Test
      run: |
        echo "TEST"
